openapi: 3.0.3
info:
  title: Driver Earnings APIs
  description: Driver Earnings APIs
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/drivers/v1'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      $ref: './securitySchemes/BearerAuth.yaml'

paths:
  /earnings/{driver_id}:
    get:
      summary: "Get Earnings' details of the Driver"
      description: "Authenticated drivers will be able to view their earnings summary."
      parameters:
        - $ref: './parameters/PathParamDriver.yaml'
      responses:
        200:
          description: "Returns earnings summary of the driver"
          content:
            application/json:
              schema:
                $ref: './schemas/driver/Earning.yaml'
        404:
          description: "No earnings"
          content:
            { }

  /earnings:
    post:
      summary: "Update Earnings"
      description: "Update Earnings' details of the driver based on ride id. It should only be called by other service."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                driver_id:
                  type: string
                ride_id:
                  type: string
      responses:
        200:
          description: "Amount added in the earnings"
          content:
            {}
        400:
          description: "Invalid request or field missing"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'