openapi: 3.0.3
info:
  title: Driver's Status Management APIs
  description: Status Management APIs
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/drivers/v1'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      $ref: './securitySchemes/BearerAuth.yaml'

paths:
  /availability:
    post:
      summary: "Driver's availability status"
      description: "Authenticated drivers will be able to update whether they are available to accept rides or not."
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/driver/DriverAvailabilityStatusUpdateRequest.yaml'
      responses:
        200:
          description: "Driver's availability status successfully updated"
          content:
            { }
        400:
          description: "Invalid request or missing fields"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'

  /location:
    post:
      summary: "Update driver's current location"
      description: "Authenticated drivers will be able to update their current location."
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/location/LocationUpdateRequest.yaml'
      responses:
        200:
          description: "Driver's location updated"
          content:
            { }
        400:
          description: "Invalid request or missing fields"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'

  /location/{driver_id}:
    get:
      summary: "Get driver's current location"
      description: "Other services can consume this api to get the Driver's latest location. It can only be accessed by other service."
      parameters:
        - $ref: './parameters/PathParamDriver.yaml'
      responses:
        200:
          description: "Driver's location fetched"
          content:
            application/json:
              schema:
                $ref: './schemas/location/Location.yaml'
        400:
          description: "Invalid request or missing fields"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'
        404:
          description: "Driver is unavailable"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'
