openapi: 3.0.3
info:
  title: Profile Management APIs
  description: Profile Management APIs
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/drivers/v1'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      $ref: './securitySchemes/BearerAuth.yaml'

paths:
  /profile/{driver_id}:
    get:
      summary: "View Driver's profile"
      description: "Authenticated drivers can view their profile."
      parameters:
        - $ref: './parameters/PathParamDriver.yaml'
      responses:
        200:
          description: "Returns Driver's profile"
          content:
            application/json:
              schema:
                $ref: './schemas/driver/Driver.yaml'
  /profile:
    put:
      summary: 'Update profile'
      description: "Authenticated drivers will be able to update some of the details in their profile."
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/driver/DriverUpdateProfileRequest.yaml'
      responses:
        200:
          description: 'Successfully updated profile'
          content:
            { }
        400:
          description: 'Validation error or missing fields'
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'