openapi: 3.0.3
info:
  title: Ride History of the Driver
  description: Ride History of the Driver
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/drivers/v1'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      $ref: './securitySchemes/BearerAuth.yaml'

paths:
  /rides/{driver_id}:
    get:
      summary: "Ride History of the Driver"
      description: "Authenticated drivers will be able to view all the history of their rides."
      parameters:
        - $ref: './parameters/PathParamDriver.yaml'
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
        - in: query
          name: limit
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "Returns all the rides of the driver in a paginated way"
          content:
            application/json:
              schema:
                $ref: './schemas/ride/RideHistory.yaml'
        404:
          description: "No rides found"
          content:
            { }