openapi: 3.0.3
info:
  title: Ride Assignment APIs for Driver
  description: Ride APIs for Driver
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/drivers/v1'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      $ref: './securitySchemes/BearerAuth.yaml'

paths:
  /ride/assignment:
    post:
      summary: "Notify all the nearby riders"
      description: "This should be called only by RideManagement Service. It will return the response as Accepted if there are any drivers within a range of 5 km radius."
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/requests/RideRequest.yaml'
      responses:
        202:
          description: "Request Accepted"
          content:
            { }
        404:
          description: "No drivers found"
          content:
            { }

  /ride/acceptance/{driver_id}:
    post:
      summary: "Accept/Reject Ride Request"
      description: "Authenticated drivers who were notified about the ride can accept or reject the ride request."
      parameters:
        - $ref: './parameters/PathParamDriver.yaml'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/requests/RideAcceptance.yaml'
      responses:
        200:
          description: "Driver will accept or reject the ride"
          content:
            { }
        409:
          description: "Ride request has already been assigned to other driver"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'
        410:
          description: "Ride request no longer exists as rider might have cancelled"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'