openapi: 3.0.3
info:
  title: Ride Status Update By Driver
  description: Ride Status Update By Driver
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/drivers/v1'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      $ref: './securitySchemes/BearerAuth.yaml'

paths:
  /ride/active/{driver_id}:
    get:
      summary: "View Active Ride Details of a Driver"
      description: "Authenticated drivers will be able to view the details of the active ride they are assigned to."
      parameters:
        - $ref: './parameters/PathParamDriver.yaml'
      responses:
        200:
          description: "Returns active ride details of the driver"
          content:
            application/json:
              schema:
                $ref: './schemas/ride/ActiveRide.yaml'
        404:
          description: "No active rides"
          content:
            { }

  /ride/active/start/{ride_id}:
    put:
      summary: "Start Ride"
      description: "Authenticated drivers will be able to start the ride once they reach the pickup location."
      parameters:
        - $ref: './parameters/PathParamRide.yaml'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/location/Location.yaml'
      responses:
        200:
          description: "Ride started"
          content:
            { }
        400:
          description: "Could not start the ride"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'

  /ride/active/end/{ride_id}:
    put:
      summary: "End Ride"
      description: "Authenticated drivers will be able to end the ride once they reach the dropoff location. It will also calculate the amount."
      parameters:
        - $ref: './parameters/PathParamRide.yaml'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/location/Location.yaml'
      responses:
        200:
          description: "Ride ended"
          content:
            { }
        400:
          description: "Could not end the ride"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'

  /ride/active/cancel/{ride_id}:
    put:
      summary: "Cancel Ride"
      description: "Authenticated drivers will be able to cancel the ride if the ride has not yet started."
      parameters:
        - $ref: './parameters/PathParamRide.yaml'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/requests/CancelRide.yaml'
      responses:
        200:
          description: "Ride cancelled. Driver can now accept rides"
          content:
            { }
        400:
          description: "Could not cancel the ride"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'

  /ride/active/completed/{ride_id}:
    put:
      summary: "Ride Completed"
      description: "This API will be called from either Payment Service or from Ride Management Service"
      parameters:
        - $ref: './parameters/PathParamRide.yaml'
      responses:
        200:
          description: "Ride completed"
          content:
            { }
        400:
          description: "Missing fields or Invalid values"
          content:
            application/json:
              schema:
                $ref: './schemas/errors/ClientErrorResponse.yaml'

  /ride/active/location/{ride_id}:
    put:
      summary: "Update location for active ride"
      description: "This API will be used from driver's device to keep updating the location of the ride."
      parameters:
        - $ref: './parameters/PathParamRide.yaml'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/requests/RideLocation.yaml'
      responses:
        200:
          description: "Location updated."
          content:
            { }
        400:
          description: ""